"""Added users, tags

Revision ID: 5976188d978
Revises: 
Create Date: 2015-03-12 17:05:00.787046

"""

# revision identifiers, used by Alembic.
revision = '5976188d978'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('key', sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('tag', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=False),
        sa.Column('username', sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(['username'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('users')
    ### end Alembic commands ###
